### ISSUE TITLE
Latest version on npm has no dist

### ISSUE THREAD

**Issue by lauriejones** [jameslnewell/react-create-component-from-tag-prop#2]
Hey James!

Missing an `.npmignore` file so npm is using your `.gitignore` and ignoring your dist folder

**Comment by jameslnewell** [comment]
Ty for the heads up! I've got the `files` key in `package.json` but `babel` was nesting the generated file one level deeper than expected so it wasn't getting published.

Should be fixed in `react-create-component-from-tag-prop@1.3.1`.
